### ISSUE TITLE
Issue running software on 2012 mac mini

### ISSUE THREAD

**Issue by dgorin1** [dgorin1/mddtoolkit#29]
My colleague Marie is getting an error when she runs this code on an old mac mini. This the the output she's getting:

cosmo@Cosmos-Mac-mini ~ % mddtoolkit -i /Users/cosmo/Desktop/Python/LABCO-Plag-Db_python.csv -c /Users/cosmo/Desktop/Python/test_config.yaml -o /Users/cosmo/Desktop/Python/storage_diff

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/mddtoolkit", line 5, in <module>
    from diffusion_kinetics.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/cli.py", line 1, in <module>
    from diffusion_kinetics.pipeline.multi_pipeline import MultiPipeline
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/pipeline/__init__.py", line 1, in <module>
    from .pipeline_config import MultiProcessPipelineConfig, SingleProcessPipelineConfig
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/pipeline/pipeline_config.py", line 4, in <module>
    import torch
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/__init__.py", line 1477, in <module>
    from .functional import *  # noqa: F403
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/functional.py", line 9, in <module>
    import torch.nn.functional as F
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/__init__.py", line 35, in <module>
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

Running multi pipeline with config:
MultiProcessPipelineConfig : (
    domains_to_model: [4, 6]
    geometry: spherical
    init: latinhypercube
    max_iters: 100000
    misfit_stat_list: ['percent_frac']
    mutation: [0.5, 1.0]
    omit_value_indices: [0, 38]
    popsize: 15
    punish_degas_early: False
    recombination: 0.7
    repeat_iterations: 10
    seed: 0
    strategy: best1bin
    tol: 1e-05
    updating: deferred
) 

================================================================================ 
Running pipeline for misfit type: percent_frac  
================================================================================

Fitting model with 4 domains
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/mddtoolkit", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/cli.py", line 15, in main
    MultiPipeline(args.output).run(args.config, args.input)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/pipeline/multi_pipeline.py", line 37, in run
    res = pipeline.run(single_pipeline_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/pipeline/single_pipeline.py", line 37, in run
    res = self.optimizer.run(config, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/optimization/diffusion_optimizer.py", line 26, in run
    objective = DiffusionObjective(
                ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/diffusion_kinetics/optimization/diffusion_objective.py", line 59, in __init__
    indices = np.where(np.isinf(self.lnd0aa))
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/_tensor.py", line 1062, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
RuntimeError: Numpy is not available

Any idea what might be causing this? It looks like Torch and Numpy aren't talking nicely with one another, but I'm not sure I follow the issue.

-Drew

**Comment by dgorin1** [comment]
Her operating system is MacOS Catalina version 10.15.7
